version: '3'
services:
  database:
    image: mysql:8.0.26
    restart: unless-stopped
    ports:
      - 3306:3306
    env_file: ./.env
    environment:
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - database
    build: .
    restart: unless-stopped
    env_file: ./.env
    volumes: 
      - .:/app
      - /app/node_modules
    ports:
      - 3333:3333
      - 9999:9999
    environment:
      - DB_HOST=database

volumes: 
  db: